/* ============================================================
 * 点读词典 — 语文写字表生字卡 + 英语单词卡
 * 语文组词: 按部编五上写字表组词(知乎组词版核对)
 * 英语音标/中文: 按译林5A单词表(搜狐版核对); 词组例句自编
 * ============================================================ */
(function () {
  'use strict';

  var H = {
    /* 第一单元 */
    '宜': { p: 'yí', d: '合适，应当', z: ['适宜', '相宜', '事不宜迟'], l: '这本书很适宜小学生阅读。' },
    '鹤': { p: 'hè', d: '一种长颈长腿的涉禽', z: ['白鹤', '丹顶鹤', '鹤发童颜'], l: '湖边站着一只白鹤。' },
    '嫌': { p: 'xián', d: '厌恶，不满意', z: ['嫌弃', '嫌恶', '讨人嫌'], l: '他从不嫌弃旧衣服。' },
    '朱': { p: 'zhū', d: '红色；姓氏', z: ['朱红', '朱砂', '朱门'], l: '墙漆成了朱红色。' },
    '嵌': { p: 'qiàn', d: '把东西卡进凹处', z: ['镶嵌', '嵌入', '嵌在'], l: '戒指上镶嵌着一颗钻石。' },
    '框': { p: 'kuàng', d: '围住四周的架子', z: ['镜框', '木框', '门框'], l: '照片装进了木框里。' },
    '匣': { p: 'xiá', d: '装东西的小盒子', z: ['匣子', '镜匣', '木匣'], l: '奶奶有个百宝匣。' },
    '哨': { p: 'shào', d: '哨子；巡逻警戒', z: ['口哨', '哨兵', '放哨'], l: '他吹了一声口哨。' },
    '恩': { p: 'ēn', d: '好处，深厚的情谊', z: ['恩情', '恩惠', '感恩'], l: '我们永远记得老师的恩情。' },
    '韵': { p: 'yùn', d: '悦耳的声音；风度', z: ['韵母', '韵味', '风韵'], l: '这首诗读起来韵味十足。' },
    '亩': { p: 'mǔ', d: '土地面积单位', z: ['一亩', '半亩', '两亩地'], l: '后园有半亩空地。' },
    '播': { p: 'bō', d: '撒种；传布', z: ['播种', '播放', '广播'], l: '春天到了，农民忙着播种。' },
    '浇': { p: 'jiāo', d: '灌水；淋', z: ['浇水', '浇灌', '浇花'], l: '记得每天给花浇水。' },
    '吩': { p: 'fēn', d: '嘱咐，口头指派', z: ['吩咐', '吩示'], l: '妈妈吩咐他把房间收拾好。' },
    '咐': { p: 'fù', d: '嘱咐（用于吩咐）', z: ['嘱咐', '吩咐'], l: '老师嘱咐我们路上小心。' },
    '亭': { p: 'tíng', d: '有顶无墙的小建筑', z: ['凉亭', '茅亭', '亭亭玉立'], l: '我们在凉亭里躲雨。' },
    '榨': { p: 'zhà', d: '压出汁水；压取', z: ['榨油', '榨汁', '压榨'], l: '花生可以用来榨油。' },
    '慕': { p: 'mù', d: '敬佩，想念', z: ['羡慕', '爱慕', '仰慕'], l: '同学们都很羡慕他。' },
    '矮': { p: 'ǎi', d: '个子低', z: ['矮小', '高矮', '低矮'], l: '弟弟比我矮半个头。' },
    '谈': { p: 'tán', d: '说话，讨论', z: ['谈话', '谈论', '交谈'], l: '我们谈了很久。' },
    '懂': { p: 'dǒng', d: '明白，理解', z: ['懂得', '懂事', '易懂'], l: '他是个懂事的孩子。' },
    '兰': { p: 'lán', d: '兰花，草本植物', z: ['兰花', '玉兰', '兰草'], l: '院子里种着几盆兰花。' },
    '箩': { p: 'luó', d: '用竹子编的盛器', z: ['箩筐', '米箩', '淘箩'], l: '爷爷用箩筐装满了稻谷。' },
    '婆': { p: 'pó', d: '老年妇女；祖母', z: ['外婆', '婆家', '老太婆'], l: '外婆做的糕饼最香。' },
    '糕': { p: 'gāo', d: '用米粉面粉做的食品', z: ['蛋糕', '糕点', '年糕'], l: '妈妈买了一块桂花糕。' },
    '饼': { p: 'bǐng', d: '扁圆形的面食', z: ['糕饼', '大饼', '月饼'], l: '中秋节的月饼真甜。' },
    '浸': { p: 'jìn', d: '泡在液体里；渗入', z: ['沉浸', '浸泡', '浸湿'], l: '桂花香浸透了整条巷子。' },
    '缠': { p: 'chán', d: '绕；纠缠', z: ['缠住', '缠绕', '缠绵'], l: '藤蔓缠绕在篱笆上。' },
    '茶': { p: 'chá', d: '用茶叶泡的饮品', z: ['茶叶', '茶水', '泡茶'], l: '爸爸喜欢喝浓茶。' },
    '捡': { p: 'jiǎn', d: '拾取', z: ['捡起', '捡拾', '捡到'], l: '他把地上的纸屑捡起来。' },
    /* 第二单元 */
    '汛': { p: 'xùn', d: '江河定期的涨水', z: ['汛期', '防汛', '春汛'], l: '汛期一到，江水猛涨。' },
    '访': { p: 'fǎng', d: '看望；调查', z: ['访问', '采访', '访友'], l: '记者去采访了老教师。' },
    '鞋': { p: 'xié', d: '穿在脚上的东西', z: ['鞋子', '皮鞋', '拖鞋'], l: '过河前要脱鞋。' },
    '挽': { p: 'wǎn', d: '拉；卷起；挽回', z: ['挽留', '挽裤', '挽回'], l: '他挽起裤腿下了水。' },
    '隔': { p: 'gé', d: '遮断，距离', z: ['相隔', '间隔', '隔开'], l: '一条小溪隔着两个村子。' },
    '懒': { p: 'lǎn', d: '不爱劳动', z: ['懒惰', '懒散', '偷懒'], l: '懒惰的人什么都做不成。' },
    '惰': { p: 'duò', d: '懈怠（懒惰）', z: ['惰性', '怠惰', '懒惰'], l: '要克服学习的惰性。' },
    '稳': { p: 'wěn', d: '安稳，不动摇', z: ['平稳', '稳定', '稳当'], l: '他稳稳地走过搭石。' },
    '衡': { p: 'héng', d: '平衡，对称', z: ['平衡', '均衡', '衡量'], l: '走搭石要掌握平衡。' },
    '协': { p: 'xié', d: '共同配合', z: ['协调', '协作', '同心协力'], l: '大家协作把船拉上了岸。' },
    '召': { p: 'zhào', d: '叫人来；呼唤', z: ['召集', '召开', '号召'], l: '老师召集班干部开会。' },
    '臣': { p: 'chén', d: '君主时代的官员', z: ['大臣', '忠臣', '君臣'], l: '蔺相如是赵国的大臣。' },
    '议': { p: 'yì', d: '讨论；意见', z: ['商议', '会议', '议论'], l: '大家商议出一个好办法。' },
    '宫': { p: 'gōng', d: '帝王的房屋', z: ['宫殿', '皇宫', '宫廷'], l: '这座宫殿非常宏伟。' },
    '献': { p: 'xiàn', d: '恭敬地送上', z: ['献给', '奉献', '贡献'], l: '他把奖品献给了老师。' },
    '诺': { p: 'nuò', d: '答应的话', z: ['诺言', '承诺', '许诺'], l: '答应的事就要守诺言。' },
    '典': { p: 'diǎn', d: '标准书籍；典礼', z: ['字典', '典礼', '经典'], l: '遇到不认识的字查字典。' },
    '抄': { p: 'chāo', d: '照写；搜查', z: ['抄写', '抄近路', '抄录'], l: '把生词抄写两遍。' },
    '罪': { p: 'zuì', d: '犯法的行为；过错', z: ['犯罪', '罪过', '认罪'], l: '他承认了自己的过错。' },
    '怯': { p: 'qiè', d: '胆小，害怕', z: ['胆怯', '怯弱', '羞怯'], l: '面对困难不能胆怯。' },
    '拒': { p: 'jù', d: '不接受', z: ['拒绝', '抗拒', '拒之门外'], l: '他拒绝了不正当的要求。' },
    '荆': { p: 'jīng', d: '带刺的灌木', z: ['荆条', '负荆请罪', '紫荆'], l: '廉颇背着荆条去请罪。' },
    '冠': { p: 'guàn', d: '居第一位；帽子(guān)', z: ['冠军', '夺冠', '桂冠'], l: '他夺得了百米冠军。' },
    '俯': { p: 'fǔ', d: '向下，低头', z: ['俯身', '俯冲', '俯视'], l: '游隼俯冲的速度极快。' },
    '喷': { p: 'pēn', d: '液体受压涌出', z: ['喷气', '喷泉', '喷出'], l: '鲸的鼻孔会喷出水柱。' },
    '枚': { p: 'méi', d: '量词，小个的东西', z: ['一枚', '不胜枚举'], l: '他获得了一枚金牌。' },
    '箭': { p: 'jiàn', d: '用弓发射的武器', z: ['火箭', '射箭', '弓箭'], l: '火箭飞向太空。' },
    '筒': { p: 'tǒng', d: '粗大的管子', z: ['竹筒', '笔筒', '万花筒'], l: '桌上放着一个笔筒。' },
    '束': { p: 'shù', d: '捆；量词', z: ['一束', '花束', '约束'], l: '他送妈妈一束鲜花。' },
    '赤': { p: 'chì', d: '红色；忠诚', z: ['赤道', '赤诚', '赤脚'], l: '赤道地区终年炎热。' },
    '圈': { p: 'quān', d: '环形；围', z: ['圆圈', '圈画', '绕圈'], l: '他在纸上画了个圆圈。' },
    '置': { p: 'zhì', d: '安放；设立', z: ['放置', '布置', '设置'], l: '教室里布置得很漂亮。' },
    '侵': { p: 'qīn', d: '强行进入，侵犯', z: ['侵略', '侵入', '侵犯'], l: '侵略者被赶了出去。' },
    '略': { p: 'lüè', d: '简单；策略', z: ['侵略', '策略', '省略'], l: '做题时要讲究策略。' },
    '筑': { p: 'zhù', d: '修建；建筑物', z: ['修筑', '建筑', '筑路'], l: '人们修筑了坚固的堤坝。' },
    '堡': { p: 'bǎo', d: '军事防守建筑', z: ['碉堡', '城堡', '堡垒'], l: '山顶上有一座碉堡。' },
    '党': { p: 'dǎng', d: '政党；亲族', z: ['党员', '入党', '同党'], l: '爷爷是老党员。' },
    '丘': { p: 'qiū', d: '小土山', z: ['山丘', '沙丘', '丘陵'], l: '村后有几座小山丘。' },
    '妨': { p: 'fáng', d: '阻碍，损害', z: ['妨碍', '妨害', '不妨'], l: '大声说话会妨碍别人。' },
    '蔽': { p: 'bì', d: '遮盖，挡住', z: ['隐蔽', '遮蔽', '掩蔽'], l: '地道是隐蔽的好地方。' },
    '陷': { p: 'xiàn', d: '掉进；凹进', z: ['陷坑', '陷进', '沦陷'], l: '路上有个陷坑要小心。' },
    '拐': { p: 'guǎi', d: '转弯；瘸走', z: ['拐弯', '拐角', '拐杖'], l: '过了拐弯就到学校了。' },
    /* 第三单元 */
    '酬': { p: 'chóu', d: '报答；报酬', z: ['酬谢', '报酬', '酬劳'], l: '海力布不要任何酬谢。' },
    '珍': { p: 'zhēn', d: '宝贵的东西', z: ['珍宝', '珍惜', '珍贵'], l: '这份友谊很珍贵。' },
    '叮': { p: 'dīng', d: '再三嘱咐；拟声', z: ['叮嘱', '叮咛', '叮咬'], l: '妈妈叮嘱我早点回家。' },
    '嘱': { p: 'zhǔ', d: '托付，告诫', z: ['嘱咐', '嘱托', '遗嘱'], l: '老师嘱咐大家注意安全。' },
    '塌': { p: 'tā', d: '倒下，下陷', z: ['崩塌', '倒塌', '塌陷'], l: '山洪暴发，山体崩塌了。' },
    '焦': { p: 'jiāo', d: '着急；火烧焦', z: ['焦急', '心焦', '焦点'], l: '大家焦急地等着消息。' },
    '誓': { p: 'shì', d: '表示决心的话', z: ['发誓', '誓言', '宣誓'], l: '他发誓要学好本领。' },
    '谎': { p: 'huǎng', d: '不真实的话', z: ['说谎', '谎言', '谎话'], l: '诚实的孩子不说谎。' },
    '延': { p: 'yán', d: '推迟；拉长', z: ['迟延', '延长', '延期'], l: '大雨使运动会延期举行。' },
    '悔': { p: 'huǐ', d: '懊恼过去的事', z: ['后悔', '悔恨', '懊悔'], l: '他很后悔没听劝告。' },
    '扶': { p: 'fú', d: '用手支持；帮助', z: ['扶起', '搀扶', '扶老携幼'], l: '他扶老奶奶过了马路。' },
    '郎': { p: 'láng', d: '男子；丈夫', z: ['新郎', '货郎', '牛郎'], l: '牛郎勤劳又善良。' },
    '爹': { p: 'diē', d: '父亲', z: ['爹娘', '爹爹', '老爹'], l: '爹娘都很疼他。' },
    '嫂': { p: 'sǎo', d: '哥哥的妻子', z: ['嫂子', '大嫂', '军嫂'], l: '嫂子待他很好。' },
    '辆': { p: 'liàng', d: '车的量词', z: ['一辆', '车辆'], l: '他家买了一辆新车。' },
    '歹': { p: 'dǎi', d: '坏的（歹毒）', z: ['歹徒', '歹意', '为非作歹'], l: '警察抓住了歹徒。' },
    '罕': { p: 'hǎn', d: '稀少', z: ['罕见', '稀罕', '人迹罕至'], l: '雪豹是珍稀罕见的动物。' },
    '纱': { p: 'shā', d: '轻薄的丝织品', z: ['纱衣', '纱布', '纱巾'], l: '她披着一件纱衣。' },
    '妻': { p: 'qī', d: '男子的配偶', z: ['妻子', '夫妻', '妻儿'], l: '牛郎和妻子过得幸福。' },
    '趟': { p: 'tàng', d: '往返的次数', z: ['一趟', '赶趟', '走一趟'], l: '他去城里走了一趟。' },
    '托': { p: 'tuō', d: '委托；衬垫', z: ['托付', '寄托', '衬托'], l: '老牛托牛郎保管牛皮。' },
    '泳': { p: 'yǒng', d: '游泳', z: ['游泳', '泳池', '仰泳'], l: '他学会了游泳。' },
    '婚': { p: 'hūn', d: '结婚', z: ['结婚', '婚礼', '婚约'], l: '他们举办了热闹的婚礼。' },
    '辈': { p: 'bèi', d: '家族的世代；一生', z: ['长辈', '一辈子', '前辈'], l: '我们要尊敬长辈。' },
    '挨': { p: 'āi', d: '靠近，顺着', z: ['挨近', '挨着', '挨家挨户'], l: '他挨着奶奶坐下。' },
    /* 第四单元 */
    '祭': { p: 'jì', d: '对死者追悼', z: ['祭拜', '祭祀', '家祭'], l: '清明节我们去祭拜先烈。' },
    '乃': { p: 'nǎi', d: '是；你的；于是', z: ['乃是', '乃翁', '乃至'], l: '失败乃是成功之母。' },
    '熏': { p: 'xūn', d: '气味侵袭；熏陶', z: ['熏陶', '熏染', '臭气熏天'], l: '书香熏陶着孩子成长。' },
    '杭': { p: 'háng', d: '杭州；姓氏', z: ['杭州', '苏杭'], l: '杭州西湖风景如画。' },
    '亥': { p: 'hài', d: '地支的第十二位', z: ['亥时', '辛亥革命'], l: '辛亥革命发生在1911年。' },
    '恃': { p: 'shì', d: '依仗，依靠', z: ['自恃', '有恃无恐', '恃才傲物'], l: '有恃无恐是要吃亏的。' },
    '哀': { p: 'āi', d: '悲伤；怜悯', z: ['悲哀', '哀伤', '哀悼'], l: '万马齐喑实在可哀。' },
    '拘': { p: 'jū', d: '限制；拘束', z: ['拘束', '拘谨', '不拘一格'], l: '选拔人才要不拘一格。' },
    '泻': { p: 'xiè', d: '液体很快地流', z: ['倾泻', '一泻千里', '腹泻'], l: '河水一泻千里奔向大海。' },
    '潜': { p: 'qián', d: '隐藏；暗中', z: ['潜入', '潜力', '潜移默化'], l: '每个孩子都有潜力。' },
    '试': { p: 'shì', d: '实验；考', z: ['考试', '试验', '尝试'], l: '他勇敢地做了尝试。' },
    '胎': { p: 'tāi', d: '幼体；轮胎', z: ['轮胎', '胎儿', '脱胎换骨'], l: '自行车的轮胎没气了。' },
    '皇': { p: 'huáng', d: '君主；盛大', z: ['皇帝', '皇宫', '堂皇'], l: '古代皇帝住在皇宫里。' },
    '履': { p: 'lǚ', d: '鞋；实行', z: ['履行', '履历', '如履薄冰'], l: '我们要履行自己的诺言。' },
    '疆': { p: 'jiāng', d: '边界；国土', z: ['边疆', '疆土', '万寿无疆'], l: '战士们守卫着祖国边疆。' },
    '毁': { p: 'huǐ', d: '破坏；烧掉', z: ['毁灭', '销毁', '毁坏'], l: '大火毁灭了这座名园。' },
    '估': { p: 'gū', d: '推测，估计', z: ['估计', '估量', '评估'], l: '这场火灾的损失难以估量。' },
    '拱': { p: 'gǒng', d: '弧形环绕', z: ['拱桥', '拱卫', '众星拱月'], l: '村口有一座石拱桥。' },
    '辉': { p: 'huī', d: '闪耀的光', z: ['光辉', '辉煌', '余辉'], l: '圆明园曾经金碧辉煌。' },
    '煌': { p: 'huáng', d: '明亮（辉煌）', z: ['辉煌', '金碧辉煌'], l: '宫殿装饰得金碧辉煌。' },
    '殿': { p: 'diàn', d: '高大的房屋', z: ['宫殿', '殿堂', '大殿'], l: '太和殿非常雄伟。' },
    '陵': { p: 'líng', d: '帝王的坟墓', z: ['陵园', '陵墓', '丘陵'], l: '烈士陵园庄严肃穆。' },
    '览': { p: 'lǎn', d: '看；观看', z: ['游览', '阅览', '博览'], l: '我们在园中游览了一整天。' },
    '境': { p: 'jìng', d: '地方；状况', z: ['环境', '边境', '境地'], l: '这里的环境很优美。' },
    '宏': { p: 'hóng', d: '广大，伟大', z: ['宏伟', '宏大', '宏图'], l: '这项工程十分宏伟。' },
    '唐': { p: 'táng', d: '朝代；姓氏', z: ['唐朝', '唐诗', '唐装'], l: '唐朝诗歌繁荣昌盛。' },
    '闯': { p: 'chuǎng', d: '猛冲；闯入', z: ['闯进', '闯祸', '闯关'], l: '侵略者闯进了圆明园。' },
    '统': { p: 'tǒng', d: '总括；一统', z: ['统一', '统治', '传统'], l: '全国统一步调抗疫。' },
    '销': { p: 'xiāo', d: '去掉；卖', z: ['销毁', '销售', '报销'], l: '罪证被统统销毁。' },
    '奉': { p: 'fèng', d: '献给；遵守', z: ['奉命', '奉献', '信奉'], l: '他奉命守卫海岛。' },
    /* 第五单元 */
    '摄': { p: 'shè', d: '吸取；拍摄', z: ['摄影', '摄氏', '摄取'], l: '太阳表面温度有五千多摄氏度。' },
    '氏': { p: 'shì', d: '姓；姓氏', z: ['姓氏', '摄氏度', '神农氏'], l: '温度计显示二十摄氏度。' },
    '殖': { p: 'zhí', d: '生育；孳生', z: ['繁殖', '养殖', '殖民'], l: '细菌繁殖得非常快。' },
    '粮': { p: 'liáng', d: '粮食', z: ['粮食', '干粮', '粮仓'], l: '农民伯伯把粮食装进粮仓。' },
    '炭': { p: 'tàn', d: '木炭；煤', z: ['木炭', '煤炭', '雪中送炭'], l: '远处的煤山埋藏着煤炭。' },
    '区': { p: 'qū', d: '地域；分别', z: ['地区', '区别', '山区'], l: '山区盛产茶叶。' },
    '杀': { p: 'shā', d: '使人或动物失去生命', z: ['杀菌', '杀虫', '杀敌'], l: '阳光能杀死细菌。' },
    '菌': { p: 'jūn', d: '微生物', z: ['细菌', '杀菌', '真菌'], l: '勤洗手可以减少细菌。' },
    '疗': { p: 'liáo', d: '医治', z: ['治疗', '疗效', '理疗'], l: '医生精心治疗病人。' },
    '鼠': { p: 'shǔ', d: '哺乳动物，俗称老鼠', z: ['松鼠', '田鼠', '鼠目寸光'], l: '松鼠有一条大尾巴。' },
    '秀': { p: 'xiù', d: '美丽；优异', z: ['清秀', '优秀', '山清水秀'], l: '松鼠面容清秀。' },
    '玲': { p: 'líng', d: '形容精细小巧', z: ['玲珑', '小巧玲珑'], l: '这条手链小巧玲珑。' },
    '珑': { p: 'lóng', d: '（玲珑）精巧细致', z: ['玲珑', '玲珑剔透'], l: '琉璃瓦玲珑剔透。' },
    '歇': { p: 'xiē', d: '休息', z: ['歇息', '歇凉', '停歇'], l: '他坐在树荫下歇凉。' },
    '窝': { p: 'wō', d: '鸟兽住的地方', z: ['鸟窝', '鸡窝', '窝藏'], l: '松鼠把窝搭在树枝分叉处。' },
    '滑': { p: 'huá', d: '光滑；滑行', z: ['光滑', '滑雪', '圆滑'], l: '松鼠的毛很光滑。' },
    '拾': { p: 'shí', d: '捡起来', z: ['拾取', '捡拾', '拾金不昧'], l: '他拾金不昧，品德高尚。' },
    '狭': { p: 'xiá', d: '窄，不宽', z: ['狭窄', '狭小', '狭路相逢'], l: '这条小巷很狭窄。' },
    '勉': { p: 'miǎn', d: '努力；鼓励', z: ['勉强', '勉励', '勤奋'], l: '他勉强挤出了一丝笑容。' },
    '梳': { p: 'shū', d: '整理（毛发）', z: ['梳理', '梳头', '梳妆'], l: '松鼠常梳理自己的毛。' },
    /* 第六单元 */
    '辞': { p: 'cí', d: '告别；言辞', z: ['辞退', '推辞', '告辞'], l: '母亲被工厂辞退了。' },
    '抑': { p: 'yì', d: '压下去（压抑）', z: ['压抑', '抑制', '抑扬顿挫'], l: '读书要抑扬顿挫。' },
    '碌': { p: 'lù', d: '繁忙（忙碌）', z: ['忙碌', '劳碌', '碌碌无为'], l: '母亲整天忙碌不停。' },
    '吊': { p: 'diào', d: '悬挂；吊灯', z: ['吊灯', '吊兰', '提心吊胆'], l: '车间里挂着一排排吊灯。' },
    '噪': { p: 'zào', d: '嘈杂的声音', z: ['噪声', '噪音', '聒噪'], l: '车间里噪声震耳欲聋。' },
    '脊': { p: 'jǐ', d: '人和动物背上中间的骨', z: ['脊背', '脊梁', '屋脊'], l: '他弯着脊背干活。' },
    '竟': { p: 'jìng', d: '居然；完毕', z: ['竟然', '毕竟', '究竟'], l: '他竟然一夜没合眼。' },
    '龟': { p: 'jūn', d: '同"皴"，皮肤因干燥开裂(jūn)', z: ['龟裂'], l: '母亲的手指都龟裂了。' },
    '哇': { p: 'wa', d: '叹词，表示惊叹', z: ['好哇', '快走哇'], l: '你跑得真快哇！' },
    '忍': { p: 'rěn', d: '忍耐，忍受', z: ['忍心', '忍受', '忍气吞声'], l: '他强忍着眼泪。' },
    '酸': { p: 'suān', d: '像醋的味道；悲痛', z: ['心酸', '酸痛', '酸甜苦辣'], l: '想到这里，鼻子一酸。' },
    '权': { p: 'quán', d: '权力；权利', z: ['权利', '职权', '权宜之计'], l: '每个人都有学习的权利。' },
    '蚕': { p: 'cán', d: '吃桑叶吐丝的昆虫', z: ['蚕茧', '养蚕', '春蚕'], l: '父亲卖茧给我买枇杷。' },
    '考': { p: 'kǎo', d: '测验；检查', z: ['考试', '考虑', '思考'], l: '考试前要认真复习。' },
    '疼': { p: 'téng', d: '痛；疼爱', z: ['疼爱', '心疼', '疼痛'], l: '父母最疼爱孩子。' },
    '席': { p: 'xí', d: '坐垫；座位', z: ['凉席', '出席', '一席话'], l: '夏天睡凉席很凉快。' },
    '糖': { p: 'táng', d: '甜味食品', z: ['糖果', '冰糖', '白糖'], l: '庙会上卖了热豆腐脑和糖果。' },
    '屑': { p: 'xiè', d: '碎末', z: ['纸屑', '木屑', '琐屑'], l: '地上撒满了纸屑。' },
    '启': { p: 'qǐ', d: '开导；开始', z: ['启发', '启示', '开启'], l: '老师的话给我很大启发。' },
    '迪': { p: 'dí', d: '开导（启迪）', z: ['启迪', '启迪智慧'], l: '这本书启迪了无数读者。' },
    '钉': { p: 'dīng', d: '金属细棍；钉子', z: ['钉子', '铁钉', '螺丝钉'], l: '墙上钉了一枚钉子。' },
    '陪': { p: 'péi', d: '伴随，陪同', z: ['陪伴', '陪同', '陪衬'], l: '父母陪伴我们成长。' },
    '毕': { p: 'bì', d: '完结；全部', z: ['毕业', '完毕', '毕竟'], l: '他即将小学毕业。' },
    '暑': { p: 'shǔ', d: '热（暑假）', z: ['暑假', '暑期', '酷暑'], l: '暑假里他读了很多书。' },
    '煮': { p: 'zhǔ', d: '把东西放水里烧', z: ['煮饭', '煮面', '煮熟'], l: '妈妈在灶前煮猪食。' },
    '枕': { p: 'zhěn', d: '睡觉时垫头的东西', z: ['枕头', '枕套', '枕边'], l: '父亲的话记在我枕边。' },
    /* 第七单元 */
    '孙': { p: 'sūn', d: '孙子；后代', z: ['子孙', '孙女', '外孙'], l: '中华民族子孙繁衍不息。' },
    '泊': { p: 'bó', d: '停船靠岸(bó)；湖(pō)', z: ['停泊', '漂泊', '湖泊'], l: '渔船停泊在枫桥边。' },
    '愁': { p: 'chóu', d: '忧虑', z: ['忧愁', '发愁', '愁眉苦脸'], l: '他一夜愁得没睡好。' },
    '寺': { p: 'sì', d: '佛教庙宇', z: ['寺庙', '寺院', '寒山寺'], l: '姑苏城外有座寒山寺。' },
    '榆': { p: 'yú', d: '榆树', z: ['榆树', '榆钱', '榆关'], l: '村口长着一棵老榆树。' },
    '畔': { p: 'pàn', d: '旁边；边界', z: ['河畔', '田畔', '江畔'], l: '月亮从东山之畔升起。' },
    '黎': { p: 'lí', d: '众多；黎明', z: ['黎明', '黎民', '巴黎'], l: '黎明时分天空泛起鱼肚白。' },
    '晕': { p: 'yùn', d: '光影扩散的圈(yùn)；头晕(yūn)', z: ['红晕', '日晕', '眼晕'], l: '东方的天空染上微微的红晕。' },
    '漆': { p: 'qī', d: '涂料；黑', z: ['漆黑', '油漆', '喷漆'], l: '夜里四周一片漆黑。' },
    '幕': { p: 'mù', d: '垂挂的帘帐', z: ['夜幕', '开幕', '幕布'], l: '夜幕降临，万籁俱寂。' },
    '愈': { p: 'yù', d: '更；痊愈', z: ['愈发', '痊愈', '愈来愈好'], l: '他的病渐渐痊愈了。' },
    '旷': { p: 'kuàng', d: '空而宽阔', z: ['旷野', '空旷', '心旷神怡'], l: '旷野上刮着凛冽的寒风。' },
    '怡': { p: 'yí', d: '愉快（怡然）', z: ['心旷神怡', '怡然自得'], l: '风声虫鸣令人心旷神怡。' },
    '逸': { p: 'yì', d: '安闲；逃走', z: ['闲逸', '安逸', '飘逸'], l: '冬晨闲逸地烤着炭火。' },
    '免': { p: 'miǎn', d: '去掉；避免', z: ['避免', '免费', '未免'], l: '要避免发生危险。' },
    '桨': { p: 'jiǎng', d: '划船的器具', z: ['船桨', '划桨', '摇桨'], l: '我们划着船桨进了榕树丛。' },
    '榕': { p: 'róng', d: '榕树', z: ['榕树', '榕城'], l: '大榕树的枝干不可计数。' },
    '纠': { p: 'jiū', d: '缠绕；纠正', z: ['纠正', '纠缠', '纠纷'], l: '老师帮我纠正了错误。' },
    '桩': { p: 'zhuāng', d: '打入地下的柱子', z: ['树桩', '木桩', '一桩事'], l: '河边立着许多木桩。' },
    '涨': { p: 'zhǎng', d: '水位升高(zhǎng)；涨大(zhàng)', z: ['涨潮', '涨水', '水涨船高'], l: '河水涨潮淹没了沙滩。' },
    '塔': { p: 'tǎ', d: '高耸的建筑物', z: ['宝塔', '铁塔', '灯塔'], l: '白塔立在山顶上。' },
    '梢': { p: 'shāo', d: '树枝的末端', z: ['树梢', '末梢', '辫梢'], l: '鸟儿落在树梢上。' },
    '暇': { p: 'xiá', d: '空闲', z: ['应接不暇', '无暇', '目不暇接'], l: '鸟太多，眼睛应接不暇。' },
    '眉': { p: 'méi', d: '眼上方的毛', z: ['眉毛', '眉头', '喜上眉梢'], l: '他皱着眉头想问题。' },
    '抛': { p: 'pāo', d: '扔，投', z: ['抛弃', '抛向', '抛球'], l: '他把石子抛进河里。' },
    /* 第八单元 */
    '耻': { p: 'chǐ', d: '羞愧；耻辱', z: ['耻辱', '羞耻', '不耻下问'], l: '敏而好学，不耻下问。' },
    '诲': { p: 'huì', d: '教导', z: ['教诲', '训诲', '诲人不倦'], l: '老师的教诲铭记在心。' },
    '谓': { p: 'wèi', d: '说；叫做', z: ['所谓', '称谓', '谓语'], l: '所谓天才，就是勤奋。' },
    '诵': { p: 'sòng', d: '读出声；背诵', z: ['朗诵', '诵读', '背诵'], l: '每天清晨他诵读古诗。' },
    '岂': { p: 'qǐ', d: '难道（岂有此理）', z: ['岂止', '岂敢', '岂有此理'], l: '心到了，眼口岂能不到？' },
    '恒': { p: 'héng', d: '持久不变的', z: ['恒心', '永恒', '持之以恒'], l: '读书贵在持之以恒。' },
    '窥': { p: 'kuī', d: '从小孔或缝里看', z: ['窥视', '窥探', '管中窥豹'], l: '管中窥豹，可见一斑。' },
    '皆': { p: 'jiē', d: '都，全是', z: ['皆是', '皆大欢喜', '比比皆是'], l: '众人皆知他的故事。' },
    '缺': { p: 'quē', d: '短少；残破', z: ['缺少', '残缺', '缺点'], l: '读书要补上缺少的部分。' },
    '舅': { p: 'jiù', d: '母亲的兄弟', z: ['舅舅', '舅妈', '大舅'], l: '舅舅给了我第一本书。' },
    '津': { p: 'jīn', d: '唾液；渡口；天津', z: ['津津有味', '天津', '问津'], l: '他读得津津有味。' },
    '斩': { p: 'zhǎn', d: '砍杀', z: ['斩首', '斩钉截铁', '过关斩将'], l: '他斩钉截铁地回答。' },
    '限': { p: 'xiàn', d: '指定的范围', z: ['无限', '限制', '界限'], l: '学海无涯，知识无限。' },
    '凯': { p: 'kǎi', d: '胜利（凯旋）', z: ['凯旋', '凯歌', '奏凯'], l: '英雄们凯旋归来。' },
    '葛': { p: 'gě', d: '姓氏(gě)；植物(gé)', z: ['诸葛', '葛藤'], l: '诸葛亮神机妙算。' },
    '述': { p: 'shù', d: '讲述；记述', z: ['讲述', '叙述', '述说'], l: '他讲述了冒险的经历。' },
    '贾': { p: 'jiǎ', d: '姓氏；商人(gǔ)', z: ['姓贾', '贾宝玉'], l: '书里有个姓贾的公子。' },
    '衰': { p: 'shuāi', d: '减弱，变弱', z: ['衰老', '衰弱', '衰败'], l: '爷爷年纪大了，身体渐衰。' },
    '刊': { p: 'kān', d: '出版物；刊登', z: ['刊物', '周刊', '刊登'], l: '他的文章刊登在刊物上。' },
    '琐': { p: 'suǒ', d: '细小，零碎', z: ['琐碎', '琐事', '烦琐'], l: '不要为琐事烦恼。' },
    '朴': { p: 'pǔ', d: '不加装饰的(pǔ)', z: ['朴素', '质朴', '朴实'], l: '这篇文章语言质朴。' },
    '篇': { p: 'piān', d: '文章；量词', z: ['篇章', '一篇', '篇幅'], l: '这是我最爱的一篇文章。' },
    '某': { p: 'mǒu', d: '代替不明确指出的名字', z: ['某人', '某种', '某天'], l: '某天下午他忽然想通了。' }
  };

  var E = {
    /* Unit 1 */
    bear: { ip: '[beə]', cn: 'n. 熊', ph: 'a big bear 一头大熊', ex: 'The bear is sleeping in the cave.' },
    forest: { ip: '[ˈfɔrist]', cn: 'n. 森林', ph: 'in the forest 在森林里', ex: 'Goldilocks walks in the forest.' },
    there: { ip: '[ðeə]', cn: 'pron. 那里（与be连用表示"有"）', ph: 'there is / there are 有', ex: 'There is a house in the forest.' },
    house: { ip: '[haus]', cn: 'n. 房子', ph: 'a big house 一座大房子', ex: 'There is a house near the river.' },
    soup: { ip: '[su:p]', cn: 'n. 汤', ph: 'a bowl of soup 一碗汤', ex: 'This soup is too hot.' },
    room: { ip: '[ru:m]', cn: 'n. 房间', ph: 'a big room 一个大房间', ex: 'The room is clean and bright.' },
    hard: { ip: '[hɑ:d]', cn: 'adj. 硬的；困难的', ph: 'too hard 太硬', ex: 'The bed is too hard.' },
    soft: { ip: '[sɔft]', cn: 'adj. 柔软的', ph: 'too soft 太软', ex: 'The sofa is soft and nice.' },
    afraid: { ip: '[əˈfreid]', cn: 'adj. 害怕的', ph: 'be afraid of 害怕…', ex: 'Goldilocks is afraid of the bears.' },
    beside: { ip: '[biˈsaid]', cn: 'prep. 在…旁边', ph: 'beside the house 在房子旁边', ex: 'There is a tree beside the house.' },
    between: { ip: '[biˈtwi:n]', cn: 'prep. 在…中间', ph: 'between the two bears 在两只熊中间', ex: 'The ball is between the chairs.' },
    really: { ip: '[ˈriəli]', cn: 'adv. 真正地，确实', ph: 'really nice 真的很好', ex: 'The soup is really nice.' },
    then: { ip: '[ðen]', cn: 'adv. 然后；那么', ph: 'and then 然后', ex: 'She drinks the soup, then she is happy.' },
    find: { ip: '[faind]', cn: 'v. 找到，发现', ph: 'find out 找出', ex: 'Goldilocks finds three bowls of soup.' },
    their: { ip: '[ðeə]', cn: 'pron. 他们的', ph: 'their house 他们的房子', ex: 'The bears come back to their house.' },
    just: { ip: '[dʒʌst]', cn: 'adv. 正好，只是', ph: 'just right 正合适', ex: 'This chair is just right.' },
    right: { ip: '[rait]', cn: 'adj. 合适的；右边的', ph: 'just right 正好', ex: 'The third bowl is just right.' },
    front: { ip: '[frʌnt]', cn: 'n. 前面', ph: 'in front of 在…前面', ex: 'There are some flowers in front of the house.' },
    her: { ip: '[hə]', cn: 'pron. 她（宾格/她的）', ph: 'her mother 她的妈妈', ex: 'Goldilocks runs to her house.' },
    help: { ip: '[help]', cn: 'v./n. 帮助', ph: 'help me 帮我', ex: 'Help! Help! 救命啊！' },
    hungry: { ip: '[ˈhʌŋgri]', cn: 'adj. 饥饿的', ph: 'hungry and thirsty 又饿又渴', ex: 'Goldilocks is hungry and thirsty.' },
    behind: { ip: '[biˈhaind]', cn: 'prep. 在…后面', ph: 'behind the door 在门后', ex: 'The cat is hiding behind the door.' },
    'in front of': { ip: '[in frʌnt ɔv]', cn: 'prep. 在…前面', ph: 'in front of the house 在房子前面', ex: 'There is a garden in front of the house.' },
    cake: { ip: '[keik]', cn: 'n. 蛋糕', ph: 'a nice cake 一个好看的蛋糕', ex: 'The cake on the table is nice.' },
    coat: { ip: '[kəut]', cn: 'n. 外套', ph: 'a new coat 一件新外套', ex: 'Put on your coat. It is cold.' },
    cup: { ip: '[kʌp]', cn: 'n. 杯子', ph: 'a cup of tea 一杯茶', ex: 'There is a cup of tea on the desk.' },
    nice: { ip: '[nais]', cn: 'adj. 好的，漂亮的', ph: 'nice juice 好喝的果汁', ex: 'This juice is really nice.' },
    juice: { ip: '[dʒu:s]', cn: 'n. 果汁', ph: 'a glass of juice 一杯果汁', ex: 'I drink orange juice in the morning.' },
    third: { ip: '[θə:d]', cn: 'n./adj. 第三', ph: 'on the third floor 在三楼', ex: 'The library is on the third floor.' },
    usually: { ip: '[ˈju:ʒuəli]', cn: 'adv. 通常', ph: 'usually get up 通常起床', ex: 'I usually read books at weekends.' },
    'e-friend': { ip: '[ˈi:frend]', cn: 'n. 网友', ph: 'my e-friend 我的网友', ex: 'I often chat with my e-friend.' },
    'years old': { ip: '[jə:z əuld]', cn: '…岁', ph: 'eleven years old 十一岁', ex: 'My e-friend is eleven years old.' },
    'one ... the other': { ip: '[wʌn ðə ˈʌðə]', cn: '一个……另一个', ph: 'One is big, the other is small. 一个大，另一个小', ex: 'It has two wings. One is big, the other is small.' },
    'come out': { ip: '[kʌm aut]', cn: '出来', ph: 'come out of the box 从盒子里出来', ex: 'The rabbit comes out of the hole.' },
    'get out': { ip: '[get aut]', cn: '出来，出去', ph: 'get out of the water 从水里出来', ex: 'Be careful when you get out of the boat.' },
    teaches: { ip: '[ˈti:tʃiz]', cn: 'v. 教（teach的三单）', ph: 'teaches English 教英语', ex: 'She teaches English in a primary school.' },
    writes: { ip: '[raits]', cn: 'v. 写（write的三单）', ph: 'writes stories 写故事', ex: 'He writes stories for children.' },
    works: { ip: '[wə:ks]', cn: 'v. 工作（work的三单）', ph: 'works hard 努力工作', ex: 'My mother works in a hospital.' },
    helps: { ip: '[helps]', cn: 'v. 帮助（help的三单）', ph: 'helps people 帮助人们', ex: 'The policeman helps the old woman.' },
    lives: { ip: '[livz]', cn: 'v. 居住（live的三单）', ph: 'lives in China 住在中国', ex: 'My e-friend lives in Australia.' },
    studies: { ip: '[ˈstʌdiz]', cn: 'v. 学习（study的三单）', ph: 'studies hard 努力学习', ex: 'He studies Chinese after school.' },
    /* Unit 2 */
    student: { ip: '[ˈstju:dənt]', cn: 'n. 学生', ph: 'a new student 一名新学生', ex: 'Nancy is a new student.' },
    show: { ip: '[ʃəu]', cn: 'v. 带领；展示', ph: 'show around 带领参观', ex: 'Yang Ling shows her around the school.' },
    around: { ip: '[əˈraund]', cn: 'adv./prep. 到处；围绕', ph: 'show ... around 带…参观', ex: 'Let me show you around.' },
    classroom: { ip: '[ˈklɑ:sru:m]', cn: 'n. 教室', ph: 'our classroom 我们的教室', ex: 'Our classroom is on the second floor.' },
    second: { ip: '[ˈsekənd]', cn: 'n./adj. 第二', ph: 'on the second floor 在二楼', ex: 'The art room is on the second floor.' },
    floor: { ip: '[flɔ:]', cn: 'n. 楼层；地板', ph: 'first floor 一楼', ex: 'Which floor do you live on?' },
    computer: { ip: '[kəmˈpju:tə]', cn: 'n. 电脑', ph: 'computer room 电脑教室', ex: 'There are many computers in the room.' },
    first: { ip: '[fə:st]', cn: 'n./adj. 第一；首先', ph: 'on the first floor 在一楼', ex: 'The music room is on the first floor.' },
    swing: { ip: '[swiŋ]', cn: 'n. 秋千', ph: 'on the swings 荡秋千', ex: 'There are two swings in the playground.' },
    push: { ip: '[puʃ]', cn: 'v. 推', ph: 'push me 推我', ex: 'Push me higher, please!' },
    heavy: { ip: '[ˈhevi]', cn: 'adj. 重的', ph: 'too heavy 太重', ex: 'The box is too heavy.' },
    stop: { ip: '[stɔp]', cn: 'v. 停下，停止', ph: 'stop the car 停车', ex: 'Stop! The door is opening.' },
    high: { ip: '[hai]', cn: 'adj./adv. 高的', ph: 'so high 那么高', ex: 'The boy can jump very high.' },
    great: { ip: '[greit]', cn: 'adj. 极大的；好极了', ph: 'That sounds great. 听起来太棒了', ex: 'The playground is really great!' },
    /* Unit 3 */
    one: { ip: '[wʌn]', cn: 'num. 一个（one…the other一个…另一个）', ph: 'one ... the other 一个…另一个', ex: 'It has two legs. One is long, the other is short.' },
    other: { ip: '[ˈʌðə]', cn: 'adj./pron. 另一个', ph: 'the other 另一个', ex: 'One is red, the other is white.' },
    body: { ip: '[ˈbɔdi]', cn: 'n. 身体', ph: 'a big body 一个大大的身体', ex: 'The panda has a fat body.' },
    no: { ip: '[nəu]', cn: 'adj. 没有；不是', ph: 'no legs 没有腿', ex: 'It has no legs, but it can swim.' },
    leg: { ip: '[leg]', cn: 'n. 腿', ph: 'four legs 四条腿', ex: 'A dog has four legs.' },
    or: { ip: '[ɔ:]', cn: 'conj. 也不，或者', ph: '... or ... …或者…', ex: 'It has no arms or legs.' },
    arm: { ip: '[ɑ:m]', cn: 'n. 手臂', ph: 'long arms 长手臂', ex: 'The monkey has long arms.' },
    wing: { ip: '[wiŋ]', cn: 'n. 翅膀', ph: 'two wings 两只翅膀', ex: 'The bird has two wings.' },
    foot: { ip: '[fut]', cn: 'n. 脚；英尺', ph: 'on foot 步行', ex: 'The duck has yellow feet.' },
    rabbit: { ip: '[ˈræbit]', cn: 'n. 兔子', ph: 'a white rabbit 一只白兔', ex: 'The rabbit has long ears.' },
    give: { ip: '[giv]', cn: 'v. 给', ph: 'give ... to ... 把…给…', ex: 'Give the apple to me, please.' },
    finger: { ip: '[ˈfiŋgə]', cn: 'n. 手指', ph: 'ten fingers 十个手指', ex: 'We write with our fingers.' },
    tail: { ip: '[teil]', cn: 'n. 尾巴', ph: 'a short tail 一条短尾巴', ex: 'The rabbit has a short tail.' },
    /* Unit 4 */
    hobby: { ip: '[ˈhɔbi]', cn: 'n. 业余爱好', ph: 'my hobbies 我的爱好', ex: 'My hobby is reading books.' },
    good: { ip: '[gud]', cn: 'adj. 好的（be good at擅长）', ph: 'be good at 擅长于', ex: 'I am good at swimming.' },
    at: { ip: '[æt]', cn: 'prep. 在（be good at中的at）', ph: 'be good at singing 擅长唱歌', ex: 'She is good at dancing.' },
    with: { ip: '[wið]', cn: 'prep. 与…一起', ph: 'play with ... 和…一起玩', ex: 'I often play with my friends.' },
    also: { ip: '[ˈɔ:lsəu]', cn: 'adv. 也', ph: 'also likes 也喜欢', ex: 'He also likes playing basketball.' },
    read: { ip: '[ri:d]', cn: 'v. 读，阅读', ph: 'read stories 读故事', ex: 'I like reading stories at night.' },
    story: { ip: '[ˈstɔ:ri]', cn: 'n. 故事', ph: 'a funny story 一个有趣的故事', ex: 'Grandpa tells me a story.' },
    play: { ip: '[plei]', cn: 'v. 玩；踢（球）；弹（琴）', ph: 'play the piano 弹钢琴', ex: 'She plays the piano every day.' },
    piano: { ip: '[piˈænəu]', cn: 'n. 钢琴', ph: 'play the piano 弹钢琴', ex: 'The girl plays the piano well.' },
    dance: { ip: '[dɑ:ns]', cn: 'v./n. 跳舞', ph: 'dance well 舞跳得好', ex: 'They both like dancing.' },
    watch: { ip: '[wɔtʃ]', cn: 'v. 观看', ph: 'watch films 看电影', ex: 'We like watching films together.' },
    film: { ip: '[film]', cn: 'n. 电影', ph: 'watch a film 看电影', ex: 'Let us watch a film this weekend.' },
    both: { ip: '[bəuθ]', cn: 'pron./adj. 两个都', ph: 'We both ... 我们俩都…', ex: 'We both like singing.' },
    sing: { ip: '[siŋ]', cn: 'v. 唱歌', ph: 'sing songs 唱歌', ex: 'The birds sing in the tree.' },
    group: { ip: '[gru:p]', cn: 'n. 组，群', ph: 'a music group 一个音乐小组', ex: 'We have a singing group.' },
    about: { ip: '[əˈbaut]', cn: 'prep. 关于', ph: 'a book about animals 关于动物的书', ex: 'This is a story about a cat.' },
    idea: { ip: '[aiˈdiə]', cn: 'n. 主意，想法', ph: 'good idea 好主意', ex: 'What a good idea!' },
    ice: { ip: '[ais]', cn: 'n. 冰', ph: 'ice hole 冰窟窿', ex: 'The ice is very cold.' },
    hole: { ip: '[həul]', cn: 'n. 洞', ph: 'in the hole 在洞里', ex: 'Sam falls into the ice hole. Look out!' },
    out: { ip: '[aut]', cn: 'adv. 出，向外', ph: 'look out 小心', ex: 'Look out! The floor is wet.' },
    wet: { ip: '[wet]', cn: 'adj. 湿的', ph: 'get wet 变湿', ex: 'My clothes are wet.' },
    /* Unit 5 */
    teacher: { ip: '[ˈti:tʃə]', cn: 'n. 老师', ph: 'an English teacher 英语老师', ex: 'My mother is a teacher.' },
    teach: { ip: '[ti:tʃ]', cn: 'v. 教', ph: 'teach English 教英语', ex: 'She teaches Maths in our school.' },
    writer: { ip: '[ˈraitə]', cn: 'n. 作家', ph: 'a famous writer 一位著名作家', ex: 'His father is a writer.' },
    write: { ip: '[rait]', cn: 'v. 写', ph: 'write stories 写故事', ex: 'He writes stories for children.' },
    work: { ip: '[wə:k]', cn: 'v./n. 工作', ph: 'work at home 在家工作', ex: 'She works at home.' },
    home: { ip: '[həum]', cn: 'n. 家', ph: 'at home 在家', ex: 'My father works at home.' },
    doctor: { ip: '[ˈdɔktə]', cn: 'n. 医生', ph: 'see a doctor 看医生', ex: 'The doctor helps sick people.' },
    sick: { ip: '[sik]', cn: 'adj. 生病的', ph: 'sick people 病人', ex: 'The nurse looks after sick people.' },
    people: { ip: '[ˈpi:pl]', cn: 'n. 人，人们', ph: 'many people 许多人', ex: 'Many people work in the factory.' },
    factory: { ip: '[ˈfæktri]', cn: 'n. 工厂', ph: 'in a factory 在工厂', ex: 'There is a big factory near my home.' },
    worker: { ip: '[ˈwə:kə]', cn: 'n. 工人', ph: 'factory workers 工厂工人', ex: 'The workers make cars.' },
    cook: { ip: '[kuk]', cn: 'n. 厨师；v. 烹调', ph: 'a good cook 好厨师', ex: 'My uncle is a good cook.' },
    driver: { ip: '[ˈdraivə]', cn: 'n. 司机', ph: 'a bus driver 公交司机', ex: 'He is a taxi driver.' },
    farmer: { ip: '[ˈfɑ:mə]', cn: 'n. 农民', ph: 'farm workers 农场工人', ex: 'The farmer grows rice.' },
    nurse: { ip: '[nə:s]', cn: 'n. 护士', ph: 'a kind nurse 一位和善的护士', ex: 'The nurse works in the hospital.' },
    policeman: { ip: '[pəˈli:smən]', cn: 'n. 警察', ph: 'a brave policeman 勇敢的警察', ex: 'The policeman helps the old man.' },
    /* Unit 6 */
    friend: { ip: '[frend]', cn: 'n. 朋友（e-friend网友）', ph: 'my e-friend 我的网友', ex: 'Peter is my e-friend.' },
    send: { ip: '[send]', cn: 'v. 发出（邮件等）', ph: 'send an email 发邮件', ex: 'I send an email to my e-friend.' },
    email: { ip: '[ˈi:meil]', cn: 'n. 电子邮件', ph: 'send emails 发电子邮件', ex: 'We often write emails.' },
    to: { ip: '[tu:]', cn: 'prep. 给；向', ph: 'send ... to ... 把…发给…', ex: 'Send the photo to me, please.' },
    live: { ip: '[liv]', cn: 'v. 居住；生活', ph: 'live in the UK 住在英国', ex: 'Where does he live?' },
    uk: { ip: '[ˌju:ˈkei]', cn: 'n. 英国', ph: 'live in the UK 住在英国', ex: 'My e-friend lives in the UK.' },
    old: { ip: '[əuld]', cn: 'adj. …岁的；老的', ph: 'eleven years old 十一岁', ex: 'He is eleven years old.' },
    study: { ip: '[ˈstʌdi]', cn: 'v./n. 学习', ph: 'study hard 努力学习', ex: 'What subjects does he study?' },
    australia: { ip: '[ɔˈstreiliə]', cn: 'n. 澳大利亚', ph: 'live in Australia 住在澳大利亚', ex: 'Kangaroos live in Australia.' },
    canada: { ip: '[ˈkænədə]', cn: 'n. 加拿大', ph: 'in Canada 在加拿大', ex: 'My uncle is in Canada now.' },
    china: { ip: '[ˈtʃainə]', cn: 'n. 中国', ph: 'in China 在中国', ex: 'The Great Wall is in China.' },
    us: { ip: '[ˌju:ˈes]', cn: 'n. 美国', ph: 'in the US 在美国', ex: 'Disneyland is in the US.' },
    go: { ip: '[gəu]', cn: 'v. 去', ph: 'go fishing 去钓鱼', ex: 'Let us go fishing this weekend.' },
    fishing: { ip: '[ˈfiʃiŋ]', cn: 'n. 钓鱼', ph: 'go fishing 去钓鱼', ex: 'He often goes fishing with his dad.' },
    tomorrow: { ip: '[təˈmɔrəu]', cn: 'adv. 明天', ph: 'see you tomorrow 明天见', ex: 'I will go to the park tomorrow.' },
    worry: { ip: '[ˈwʌri]', cn: 'v. 担心', ph: 'don\'t worry 别担心', ex: 'Don\'t worry, I can help you.' },
    sit: { ip: '[sit]', cn: 'v. 坐', ph: 'sit by the river 坐在河边', ex: 'They sit by the river and fish.' },
    by: { ip: '[bai]', cn: 'prep. 在…旁边', ph: 'by the river 在河边', ex: 'There is a tree by the house.' },
    wait: { ip: '[weit]', cn: 'v. 等，等待', ph: 'wait a minute 等一会儿', ex: 'Wait a minute, please!' },
    minute: { ip: '[ˈminit]', cn: 'n. 分钟', ph: 'wait a minute 等一下', ex: 'I will be back in ten minutes.' },
    /* Unit 7 */
    weekend: { ip: '[ˈwi:kend]', cn: 'n. 周末', ph: 'at weekends 在周末', ex: 'What do you do at weekends?' },
    visit: { ip: '[ˈvizit]', cn: 'v. 拜访；参观', ph: 'visit my grandparents 看望祖父母', ex: 'I usually visit my grandparents at weekends.' },
    grandparent: { ip: '[ˈgrændpeərənt]', cn: 'n. 祖父/母', ph: 'my grandparents 我的祖父母', ex: 'My grandparents live in the countryside.' },
    very: { ip: '[ˈveri]', cn: 'adv. 非常', ph: 'very much 非常', ex: 'I love my dog very much.' },
    much: { ip: '[mʌtʃ]', cn: 'adv. 非常；多', ph: 'very much 非常', ex: 'Thank you very much.' },
    often: { ip: '[ˈɔfn]', cn: 'adv. 经常', ph: 'often play 经常玩', ex: 'He often plays football after school.' },
    chat: { ip: '[tʃæt]', cn: 'v./n. 聊天', ph: 'chat on the Internet 网上聊天', ex: 'I sometimes chat with my e-friend on the Internet.' },
    internet: { ip: '[ˈintənet]', cn: 'n. 互联网', ph: 'on the Internet 在网上', ex: 'We can learn on the Internet.' },
    always: { ip: '[ˈɔ:lweiz]', cn: 'adv. 总是', ph: 'always get up early 总是早起', ex: 'She always gets up at six.' },
    sometimes: { ip: '[ˈsʌmtaimz]', cn: 'adv. 有时', ph: 'sometimes go 有时去', ex: 'Sometimes I go to the cinema.' },
    cinema: { ip: '[ˈsinəmə]', cn: 'n. 电影院', ph: 'go to the cinema 去看电影', ex: 'We go to the cinema on Sundays.' },
    lot: { ip: '[lɔt]', cn: 'n. 许多（a lot）', ph: 'a lot 很多', ex: 'She plays the piano a lot.' },
    come: { ip: '[kʌm]', cn: 'v. 来；出来', ph: 'come out 出来', ex: 'The sun comes out from behind the hill.' },
    get: { ip: '[get]', cn: 'v. 得到；变得', ph: 'get out 出来', ex: 'The bird gets out of the cage.' },
    /* Unit 8 */
    christmas: { ip: '[ˈkrisməs]', cn: 'n. 圣诞节', ph: 'at Christmas 在圣诞节', ex: 'We buy presents at Christmas.' },
    buy: { ip: '[bai]', cn: 'v. 买', ph: 'buy presents 买礼物', ex: 'People buy presents for children.' },
    present: { ip: '[ˈpreznt]', cn: 'n. 礼物', ph: 'Christmas presents 圣诞礼物', ex: 'I put the present under the tree.' },
    tree: { ip: '[tri:]', cn: 'n. 树（Christmas tree圣诞树）', ph: 'Christmas tree 圣诞树', ex: 'The Christmas tree looks pretty.' },
    father: { ip: '[ˈfɑ:ðə]', cn: 'n. 父亲（Father Christmas圣诞老人）', ph: 'Father Christmas 圣诞老人', ex: 'Father Christmas puts presents in the stockings.' },
    next: { ip: '[nekst]', cn: 'adj. 接着的，然后', ph: 'next week 下周', ex: 'First we sing, next we dance.' },
    put: { ip: '[put]', cn: 'v. 放', ph: 'put ... on ... 把…放在…上', ex: 'We put a stocking on the bed.' },
    pretty: { ip: '[ˈpriti]', cn: 'adj. 漂亮的', ph: 'a pretty girl 一个漂亮的女孩', ex: 'The card is very pretty.' },
    thing: { ip: '[θiŋ]', cn: 'n. 东西，物品', ph: 'pretty things 漂亮的东西', ex: 'We put pretty things on the tree.' },
    look: { ip: '[luk]', cn: 'v. 看起来；看', ph: 'look happy 看起来开心', ex: 'You look happy today.' },
    eve: { ip: '[i:v]', cn: 'n. 前夜（Christmas Eve平安夜）', ph: 'Christmas Eve 平安夜', ex: 'We wait for presents on Christmas Eve.' },
    stocking: { ip: '[ˈstɔkiŋ]', cn: 'n. 长筒袜', ph: 'a big stocking 一只大长袜', ex: 'Children put stockings on their beds.' },
    for: { ip: '[fɔ:]', cn: 'prep. 为；等待（wait for）', ph: 'wait for 等待', ex: 'We wait for Father Christmas.' },
    finally: { ip: '[ˈfainəli]', cn: 'adv. 最后', ph: 'first ... finally 首先…最后…', ex: 'Finally, we have a big lunch.' },
    day: { ip: '[dei]', cn: 'n. 天（Christmas Day圣诞节）', ph: 'Christmas Day 圣诞节当天', ex: 'We get up early on Christmas Day.' },
    early: { ip: '[ˈə:li]', cn: 'adv./adj. 早', ph: 'get up early 早起', ex: 'She gets up early every day.' },
    turkey: { ip: '[ˈtə:ki]', cn: 'n. 火鸡；火鸡肉', ph: 'eat turkey 吃火鸡', ex: 'People eat turkey at Christmas.' },
    pudding: { ip: '[ˈpudiŋ]', cn: 'n. 布丁', ph: 'Christmas pudding 圣诞布丁', ex: 'The pudding is sweet and nice.' },
    all: { ip: '[ɔ:l]', cn: 'adj./adv. 全部；都', ph: 'we all ... 我们都…', ex: 'We all have a good time.' },
    time: { ip: '[taim]', cn: 'n. 时间；次（have a good time玩得开心）', ph: 'have a good time 玩得愉快', ex: 'They all have a good time.' },
    card: { ip: '[kɑ:d]', cn: 'n. 卡片', ph: 'a Christmas card 圣诞卡', ex: 'I make a card for my teacher.' },
    children: { ip: '[ˈtʃildrən]', cn: 'n. 孩子们（child的复数）', ph: 'children\'s day 儿童节', ex: 'The children sing Christmas songs.' },
    message: { ip: '[ˈmesidʒ]', cn: 'n. 信息，消息', ph: 'write a message 写留言', ex: 'I write a message on the card.' },
    merry: { ip: '[ˈmeri]', cn: 'adj. 愉快的（Merry Christmas圣诞快乐）', ph: 'Merry Christmas! 圣诞快乐！', ex: 'Merry Christmas, everyone!' },
    song: { ip: '[sɔŋ]', cn: 'n. 歌曲', ph: 'sing songs 唱歌', ex: 'We sing Christmas songs together.' },
    wrong: { ip: '[rɔŋ]', cn: 'adj. 有毛病的，错的', ph: 'what\'s wrong 怎么了', ex: 'What\'s wrong with you?' },
    him: { ip: '[him]', cn: 'pron. 他（宾格）', ph: 'play with him 和他玩', ex: 'We buy a present for him.' },
    letter: { ip: '[ˈletə]', cn: 'n. 信', ph: 'write a letter 写信', ex: 'She writes a letter to her friend.' },
    storybook: { ip: '[ˈstɔ:ribuk]', cn: 'n. 故事书', ph: 'read a storybook 读故事书', ex: 'He reads a storybook before bed.' },
    after: { ip: '[ˈɑ:ftə]', cn: 'prep. 在…以后', ph: 'after school 放学后', ex: 'We play football after school.' }
  };

  window.KBG_DICT = { han: H, en: E };
})();
