const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const ctx={window:{}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../app-tools.js'),'utf8'),ctx);
const tools=ctx.window.AppTools;
assert.equal(tools.dayKey('invalid'),'');
assert.equal(tools.minutes('23:59'),1439);assert.equal(tools.minutes('25:12'),null);assert.equal(tools.minutes('12:60'),null);
const entries=[{name:'钢琴',dow:1,start:'18:00',end:'19:00'}];
assert.ok(tools.extraError({name:'吉他',dow:1,start:'18:30',end:'19:30'},entries));
assert.equal(tools.extraError({name:'吉他',dow:1,start:'19:00',end:'20:00'},entries),'');
assert.equal(tools.extraError({name:'钢琴',dow:1,start:'18:30',end:'19:30'},entries,0),'');
assert.ok(tools.extraError({name:'吉他',dow:1,start:'20:00',end:'19:00'},entries));
const log={'2026-09-08':{piano:true},'2026-09-09':{piano:true}};
assert.equal(tools.streak(log,'piano','2026-09-10T12:00:00'),2);
assert.equal(tools.streak(log,'piano','2026-09-11T12:00:00'),0);
log['2026-09-10']={piano:true};assert.equal(tools.streak(log,'piano','2026-09-10T12:00:00'),3);
const defaults={points:30,pet:{owned:['classic'],hunger:80,thirst:80,mood:80,energy:80,xp:0},schedule:{grid:{1:[],2:[],3:[],4:[],5:[]},times:[],extra:[]},checkins:{items:[],log:{}},study:{},counters:{feeds:0}};
const backup=JSON.parse(JSON.stringify(defaults));backup.arcade={records:{4:{stars:3,score:20}}};backup.study.x={finished:true};
const restored=tools.restore(backup,defaults);assert.equal(restored.arcade.records[4].stars,3);assert.ok(restored.study.x.tasks);assert.equal(backup.study.x.tasks,undefined);
assert.throws(()=>tools.restore({pet:{}},defaults));
const broken=JSON.parse(JSON.stringify(backup));broken.schedule.grid[1]='bad';assert.throws(()=>tools.restore(broken,defaults));
const badPoints=JSON.parse(JSON.stringify(backup));badPoints.points=-10;assert.throws(()=>tools.restore(badPoints,defaults));
console.log('PASS dates, checkin streaks, time overlap validation and backup validation');
